# Generated by Django 5.0 on 2024-01-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundshorus',
            name='value',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
