# Generated by Django 5.0 on 2023-12-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JurosTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=15)),
                ('total_invest', models.FloatField()),
                ('juros', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
