# Generated by Django 5.0 on 2023-12-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jurostable',
            old_name='juros',
            new_name='value_month',
        ),
        migrations.RenameField(
            model_name='jurostable',
            old_name='total',
            new_name='value_rentability',
        ),
        migrations.RenameField(
            model_name='jurostable',
            old_name='total_invest',
            new_name='value_start',
        ),
        migrations.RemoveField(
            model_name='jurostable',
            name='month',
        ),
    ]
