# Generated by Django 5.0 on 2023-12-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_tablefuturefees'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsertValuesAporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_patrimonio', models.FloatField()),
                ('juros_recebido', models.FloatField()),
                ('patrimonio_total', models.FloatField()),
            ],
        ),
    ]
